### ISSUE TITLE
README misleading regarding "upstream"

### ISSUE THREAD

**Issue by RhysU** [arcfide/chez-srfi#11]
I'm new to this space and found the README language around the Scheme Libraries project to be misleading ('You can let us know by "asking a question" at the Scheme Libraries project page: https://launchpad.net/scheme-libraries').  I gather arcfide/chez-srfi is the clearing house for this effort, but it takes some staring at commit histories to figure that out.  Please consider amending the README to indicate the linkage is stale.

**Comment by arcfide** [comment]
Thanks for the comment, I have made an attempt at clarifying this with a new README.
