### ISSUE TITLE
include/resolve macro fails with chez-scheme-9.4

### ISSUE THREAD

**Issue by ChrisVine** [arcfide/chez-srfi#2]
The path parsing carried out by the include/resolve macro fails with chez-scheme-9.4.  To get it to work, I had to apply the attached patch.
[include.sls.txt](https://github.com/arcfide/chez-srfi/files/271460/include.sls.txt)

**Comment by arcfide** [comment]
Thanks for the note. I haven't been able to verify this patch yet as I haven't made the time, but I'll try to get to this when I can.

**Comment by gwatt** [comment]
@arcfide This patch does seem to allow me to load the srfis from any directory.
Setup:
1. CHEZLIBDIRS environment variable contains the parent directory to this repo.
2. This repo is checked out into a directory named "srfi"

Without this patch I receive the following error:
```
Exception in include/resolve: cannot find file in search paths with irritants
("srfi/%3a1/srfi-1-reference.scm"
  ("/home/gmw/lib/chez/srfi/:1"
   "/home/gmw/lib/chez/srfi/:1"
   "/home/gmw/lib/chez/srfi"
   "/home/gmw/lib/chez/srfi" "."))
```

**Comment by gwatt** [comment]
This allows me to import the srfi libraries from any directory, provided this repo is checked out into a directory named "srfi". Without this patch I receive the following error:
```
Exception in include/resolve: cannot find file in search paths with irritants
("srfi/%3a1/srfi-1-reference.scm"
  ("/home/gmw/lib/chez/srfi/:1"
    "/home/gmw/lib/chez/srfi/:1"
    "/home/gmw/lib/chez/srfi"
    "/home/gmw/lib/chez/srfi"
    "."))

This is reproducible with the following steps:
1. Have a directory in CHEZLIBDIRS (call it "~/lib/chez")
2. Have the repository checked out into "~/lib/chez/srfi"
3. Run scheme from anywhere NOT in "~/lib/chez"
4. import any srfi

Without this patch, you can only load from the repo's parent directory ("~/lib/chez") 
```

**Comment by arcfide** [comment]
Fixed and incorporated. Thanks.
