### ISSUE TITLE
SRFI 146: Mappings

### ISSUE THREAD

**Issue by amirouche** [arcfide/chez-srfi#22]
What are the requirements for getting SRFI 146 aka. mapping into the repository?

**Comment by weinholt** [comment]
Submit it as a pull request and I guess it'll be merged without too much fuss.

**Comment by arcfide** [comment]
Just to make an official statement, follow the basic pattern of the rest of the repository, ensure that it works well with Chez Scheme, and submit a pull request. After that, if it all looks good, I won't have an issue with merging it in.
