### ISSUE TITLE
Out-of-context identifier in SRFI 42

### ISSUE THREAD

**Issue by weinholt** [arcfide/chez-srfi#35]
The SRFI-42 implementation uses `SRFI-23-error->R6RS` and then uses `error` from inside a macro. This makes Chez Scheme (and apparently no other implementation) complain: "attempt to reference out-of-context identifier error":

https://github.com/arcfide/chez-srfi/blob/5ff9fae299a4933188ce7cd1a225a3c26036ef0d/%253a42/eager-comprehensions.sls#L28

```scheme
Chez Scheme Version 9.5.2
Copyright 1984-2019 Cisco Systems, Inc.

> (import (srfi :42 eager-comprehensions))
> (list-ec (: i 5) (* i i))
Exception: attempt to reference out-of-context identifier error
Type (debug) to enter the debugger.
> 
```

This same class of bug was fixed in SRFI 67 by @akeep in https://github.com/arcfide/chez-srfi/commit/bae03a59b8039d4a9edccdb15711757316b0f869

(Thanks to Francesco Montanari for reporting this at https://gitlab.com/akkuscm/akku/issues/42)

**Comment by arcfide** [comment]
I've incorporated the fix given by @akeep for 67 in 6541ad8ca74fb6d1f29c8eddb582e14424725c79. 

I haven't tested this though, so it would be better if you could confirm that things are working right.

**Comment by arcfide** [comment]
I'll close once I get confirmation that the fix works.

**Comment by weinholt** [comment]
The SRFI 42 library works in Chez Scheme now. Thanks!
