### ISSUE TITLE
bug in srfi-1 fold-right 

### ISSUE THREAD

**Issue by amirouche** [arcfide/chez-srfi#42]
The last line of:

https://github.com/arcfide/chez-srfi/blob/5cfad653d2f0a5fba59085ee3686db91702b6963/%253a1/srfi-1-reference.scm#L899-L901

`lis1` should be `lis`

**Comment by amirouche** [comment]
There is also a bug with `fold-right` and `fold-left` when there is more than two lists passed as arguments.

**Comment by amirouche** [comment]
There is few tests at https://github.com/srfi-explorations/srfi-test

**Comment by arcfide** [comment]
Thanks for the report, if you can file a pull request against this repository I would be happy to merge in the fixes.

**Comment by amirouche** [comment]
Fixed in https://github.com/arcfide/chez-srfi/pull/61
