### ISSUE TITLE
Port arew's libraries to chez-srfi

### ISSUE THREAD

**Issue by amirouche** [arcfide/chez-srfi#48]
I put together [almost all](https://github.com/arew-scheme/arew-scheme/issues/3#issue-589796046) red and tangerine libraries of R7RS as R6RS libraries.

I am wondering whether you would accept pull requests to merge this work into chez-srfi. I will also rework the tests to make them work with SRFI-64.

What do you think?

**Comment by arcfide** [comment]
Sure, I'm happy to see this repo contain more SRFIs in it.

**Comment by amirouche** [comment]
Thanks!
