### ISSUE TITLE
Avoid the use of make-coroutine-generator in srfi-158

### ISSUE THREAD

**Issue by amirouche** [arcfide/chez-srfi#55]
With Chez Scheme, make-coroutine-generator is slow compared to the same code that does not rely on call/cc and call/1cc.

Those can be implemented without `make-coroutine-generator`

- `gtake`
- `make-for-each-generator`

Maybe `make-unfold-generator` can be implemented without `make-coroutine-generator`

**Comment by amirouche** [comment]
I do not see how to implement `make-for-each-generator` without `make-coroutine-generator` some for `unfold`.

Fixed gtake in https://github.com/arcfide/chez-srfi/pull/63

**Comment by arcfide** [comment]
I'll go ahead and close this then as mostly done. Feel free to submit a PR for `make-for-each-generator` if you figure it out.
