### ISSUE TITLE
(srfi :67 comparison-procedures) is not usable in Chez Scheme

### ISSUE THREAD

**Issue by weinholt** [arcfide/chez-srfi#6]
Chez doesn't like something about the SRFI-23-error->R6RS procedure used in %3a67/compare-procedures.sls. The error invocation in e.g. if3 gives an out-of-context error:

```Scheme
Chez Scheme Version 9.5
Copyright 1984-2017 Cisco Systems, Inc.

> (import (srfi :67 compare-procedures))
> (if3 1 'less 'equal 'greater)
Exception: attempt to reference out-of-context identifier error
Type (debug) to enter the debugger.
> (debug)
debug> i
#<system continuation in chi-expr>                                : sl
  continuation:          #<system continuation in dobody>
  frame variables:
  0: (("m" top) #[#{extensible-ribcage cqxefau3fa3vz4m0-1} ()] ...)
  1: #f
  2: #<eq hashtable>
  3: #(((...) displaced-lexical . "out-of-phase identifier") (61) ...)
  4: (error "comparison value not in {-1,0,1}")
#<system continuation in chi-expr>                                : 
```

**Comment by akeep** [comment]
Sorry it took me a little while to look into this.  It looks like the original compare-procedures code was attempting to play games with the SRFI 23 error call syntax to produce the R6RS error syntax.  I'm not really sure why it was going to this effort, but it was resulting in an out-of-phase identifier.

I have a fix on my fork that simply removes the (broken) translator and instead calls the SRFI 23 error (which in turn just calls the r6rs error, so it is not like you're losing anything).

Anyway, I'll make a pull request for with this fix in it.

**Comment by arcfide** [comment]
Merged pull request. @weinholt, could you please confirm that this pull request fixes things for you on your end as well? I'll close this issue once you confirm.

**Comment by weinholt** [comment]
I can confirm that bae03a59b8039 works as a fix.

The intention of the error trick is to get the "who" argument automatically from the define form. Chez is correct to reject this particular use, the identifier the macro creates is indeed used outside the context where it is valid. Fixing the macro is a bit too much effort to be worth it.

**Comment by arcfide** [comment]
Closing as fixed. Many thanks @akeep !
