### ISSUE TITLE
(srfi :14 char-sets) only handles latin-1

### ISSUE THREAD

**Issue by weinholt** [arcfide/chez-srfi#9]
The SRFI-14 implementation only handles latin-1 and tends to crash in string-ref when given characters above #\xff.

I plan to fix this rather soon, but first I wanted to open this issue and see if anyone already knows about a working implementation.

**Comment by arcfide** [comment]
Unfortunately, I do not have any experience with this recently. I would welcome patches that fix the issue. Perhaps someone else already has a fix for this?

**Comment by weinholt** [comment]
I've adapted the Scheme 48 code and pushed it to the srfi-14 branch of weinholt/chez-srfi. Test cases are passing and even tests/regexp.sps passes all tests now. I want to try it out in some applications first before I open up a PR.

This project doesn't have any CI tests. Are you open to setting up Travis CI if I write a .travis.yml file?
